version: "3.9"

services:

  postgres:
    container_name: postgres-split
    image: "postgres:14.1-alpine"
    command: ["-c", "max_connections=200"]
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "split"
      POSTGRES_PASSWORD: "root"
